WebApplication3/Controllers/AlunoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.InteropServices;
using System.Web.Mvc;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class AlunoController : Controller
    {
        // GET: Aluno
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Listar()
        {
            Aluno.GerarLista(Session);
            return View(Session["ListaAluno"] as List<Aluno>);
        }
        public ActionResult Exibir(int id)
        {
            return View((Session["ListaAluno"] as List<Aluno>).ElementAt(id));
        }

        public ActionResult Delete(int id)
        {
            return View((Session["ListaAluno"] as List<Aluno>).ElementAt(id));
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new Aluno());
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View((Session["ListaAluno"] as List<Aluno>).ElementAt(id));
        }


        [HttpPost]
        [ValidateAntiForgeryToken]

        public ActionResult Delete(int id, Aluno aluno)
        {
            Aluno.Procurar(Session, id)?.Excluir(Session);
            return RedirectToAction("Listar");
        }


        public ActionResult Create(Aluno aluno)
        {
            aluno.Adicionar(Session);
            return RedirectToAction("Listar");
        }

        public ActionResult Edit(int id, Aluno aluno)
        {
            Aluno.Procurar(Session, id)?.Editar(Session, aluno, id);
            return RedirectToAction("Listar");
        }


    }
}

WebApplication3/Controllers/CarroController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class CarroController : Controller
    {
        // GET: Carro
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Listar()
        {
            Carro.GerarLista(Session);
            return View(Session["ListaCarro"] as List<Carro>);
        }
        public ActionResult Exibir(int id)
        {
            return View((Session["ListaCarro"] as List<Carro>).ElementAt(id));
        }

        public ActionResult Delete(int id)
        {
            return View((Session["ListaCarro"] as List<Carro>).ElementAt(id));
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new Carro());
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View((Session["ListaCarro"] as List<Carro>).ElementAt(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Carro carro)
        {
            Carro.Procurar(Session, id)?.Excluir(Session);
            return RedirectToAction("Listar");
        }
        public ActionResult Create(Carro carro)
        {
            carro.Adicionar(Session);
            return RedirectToAction("Listar");
        }

        public ActionResult Edit(int id, Carro carro)
        {
            Carro.Procurar(Session, id)?.Editar(Session, carro, id);
            return RedirectToAction("Listar");
        }


    }
}

WebApplication3/Controllers/CelularController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class CelularController : Controller
    {
        // GET: Celular
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Listar()
        {
            Celular.GerarLista(Session);
            return View(Session["ListaCelular"] as List<Celular>);
        }
        public ActionResult Exibir(int id)
        {
            return View((Session["ListaCelular"] as List<Celular>).ElementAt(id));
        }

        public ActionResult Delete(int id)
        {
            return View((Session["ListaCelular"] as List<Celular>).ElementAt(id));
        }
        [HttpGet]
        public ActionResult Create()
        {
            return View(new Celular());
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View((Session["ListaCelular"] as List<Celular>).ElementAt(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Celular celular)
        {
            Celular.Procurar(Session, id)?.Excluir(Session);
            return RedirectToAction("Listar");
        }
        public ActionResult Create(Celular celular)
        {
            celular.Adicionar(Session);
            return RedirectToAction("Listar");
        }

        public ActionResult Edit(int id, Celular celular)
        {
            Celular.Procurar(Session, id)?.Editar(Session, celular, id);
            return RedirectToAction("Listar");
        }
    }
}

WebApplication3/Controllers/EventoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class EventoController : Controller
    {
        // GET: Evento
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Listar()
        {
            Evento.GerarLista(Session);
            return View(Session["ListaEvento"] as List<Evento>);
        }
        public ActionResult Exibir(int id)
        {
            return View((Session["ListaEvento"] as List<Evento>).ElementAt(id));
        }

        public ActionResult Delete(int id)
        {
            return View((Session["ListaEvento"] as List<Evento>).ElementAt(id));
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View(new Evento());
        }
        [HttpGet]
        public ActionResult Edit(int id)
        {
            return View((Session["ListaEvento"] as List<Evento>).ElementAt(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, Evento evento)
        {
            Evento.Procurar(Session, id)?.Excluir(Session);
            return RedirectToAction("Listar");
        }
        public ActionResult Create(Evento evento)
        {
            evento.Adicionar(Session);
            return RedirectToAction("Listar");
        }

        public ActionResult Edit(int id, Evento evento)
        {
            Evento.Procurar(Session, id)?.Editar(Session, evento, id);
            return RedirectToAction("Listar");
        }
    }
}

WebApplication3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication3/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

WebApplication3/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

WebApplication3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <div class="container">
        <div class="row">
            <div class="col">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Lista de alunos</h5>
                        <p class="card-text">Lista de alunos para visualizar, editar, excluir e adicionar</p>
                        @Html.ActionLink("Clique aqui", "Listar", "Aluno", new { area = "" }, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Lista de Carros</h5>
                        <p class="card-text">Lista de carros para visualizar, editar, excluir e adicionar</p>
                        @Html.ActionLink("Clique aqui", "Listar", "Carro", new { area = "" }, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Lista de celular</h5>
                        <p class="card-text">Lista de celulares para visualizar, editar, excluir e adicionar</p>
                        @Html.ActionLink("Clique aqui", "Listar", "Celular", new { area = "" }, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card" style="width: 18rem;">
                    <div class="card-body">
                        <h5 class="card-title">Lista de evento</h5>
                        <p class="card-text">Lista de eventos para visualizar, editar, excluir e adicionar</p>
                        @Html.ActionLink("Clique aqui", "Listar", "Evento", new { area = "" }, new { @class = "btn btn-primary" })
                    </div>
                </div>
            </div>
        </div>
    </div>
    
</main>